### ISSUE TITLE
Crash during cleanup of job submission

### ISSUE THREAD

**Issue by syntheticgio** [syntheticgio/tcga_varscan_pipeline#2]
Currently getting a crash after all jobs appear to be submitted successfully.  Seems to be in the update of the createrunningsample and then in the samtoolssort table.  Assume it is something broken with the previous recording system since this has changed (probably python3 issue with key, value from dict)

```
Table name: RunningSamples
ERROR:tornado.application:Uncaught exception POST /createrunningsample/ (10.128.0.39)
HTTPServerRequest(protocol='http', host='10.128.0.4:8081', method='POST', uri='/createrunningsample/', version='HTTP/1.1', remote_ip='10.128.0.39')
Traceback (most recent call last):
  File "/home/torcivia/.local/lib/python3.5/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/torcivia/pipeline/tcga_varscan_pipeline/server/server.py", line 183, in post
    sqlstr = self.construct_sql("RunningSamples", json_body)
  File "/home/torcivia/pipeline/tcga_varscan_pipeline/server/server.py", line 45, in construct_sql
    for key, value in json_object.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
ERROR:tornado.access:500 POST /createrunningsample/ (10.128.0.39) 3.15ms
In the construct sql method...
Table name: SamtoolsSort
ERROR:tornado.application:Uncaught exception POST /samtoolssort/ (10.128.0.39)
HTTPServerRequest(protocol='http', host='10.128.0.4:8081', method='POST', uri='/samtoolssort/', version='HTTP/1.1', remote_ip='10.128.0.39')
Traceback (most recent call last):
  File "/home/torcivia/.local/lib/python3.5/site-packages/tornado/web.py", line 1701, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/torcivia/pipeline/tcga_varscan_pipeline/server/server.py", line 301, in post
    sqlstr = self.construct_sql("SamtoolsSort", json_body)
  File "/home/torcivia/pipeline/tcga_varscan_pipeline/server/server.py", line 45, in construct_sql
    for key, value in json_object.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
ERROR:tornado.access:500 POST /samtoolssort/ (10.128.0.39) 1.91ms
```

**Comment by syntheticgio** [comment]
Closed by #5
